[project]
name = "qbc-store-data-analysis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ParsaAp0", email = "parsaadlparvar.201.1384@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
qbc-store-data-analysis-project = "qbc_store_data_analysis_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
