[project]
name = "qbc-store-data-analysis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ParsaAp0", email = "parsaadlparvar.201.1384@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "interpret>=0.7.8",
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "mlflow>=1.27.0",
    "nbformat>=5.11.1",
    "numpy>=2.5.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pip>=26.2.1",
    "plotly>=7.0.0",
    "protobuf==3.20.3",
    "scikit-learn>=1.9.0",
    "setuptools>=69.0.0,<75.0.0",
    "xgboost>=3.4.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
